class NotFoundException(Exception):
    pass


class ResoruceAlreadyExistsException(Exception):
    pass
